If install fails, stop and say so.
git-svn-id: https://ravl.svn.sourceforge.net/svnroot/ravl/main/Ravl@27 7226f50c-d813-0410-99bf-979b288ab488

diff --git a/install b/install
--- a/install
+++ b/install
@@ -71,10 +71,22 @@ fi
 echo "Architecture: '${ARC}'"
 
 # Install make system.
-${MAKE} -C QMake -f ./QMake.mk MAKEHOME=`pwd`/QMake PROJECT_OUT=${INSTALL_SITE} PROCS=1 FULLBUILDSRC='BASE_VAR=none'
+if ${MAKE} -C QMake -f ./QMake.mk MAKEHOME=`pwd`/QMake PROJECT_OUT=${INSTALL_SITE} PROCS=1 FULLBUILDSRC='BASE_VAR=none' ; then
+  true
+else
+  echo "ERROR: Failed to install make system. "
+  echo "Aborting installation. "
+  exit 1
+fi
 
 # Compile libraries
-${MAKE} -f ${INSTALL_SITE}/Tools/QMake/QMake.mk PROJECT_OUT=${INSTALL_SITE} fullbuild  FULLBUILDSRC='BASE_VAR=none'
+if ${MAKE} -f ${INSTALL_SITE}/Tools/QMake/QMake.mk PROJECT_OUT=${INSTALL_SITE} fullbuild  FULLBUILDSRC='BASE_VAR=none' ; then 
+  true
+else
+  echo "ERROR: Failed to build libraries. "
+  echo "Aborting installation. "
+  exit 1
+fi
 
 # Print some usage instructions
 echo "Use the following alias for compilation.  PROJECT_OUT controls the directory "
